F #227: Fix netplan vs renderer vs NM
- Remove unused ec2 build to make space for alpine apk
- Change service dependencies
- Introduce new service one-context-online
- Add new context type online next to the local and network

Signed-off-by: Petr Ospalý <pospaly@opennebula.io>

diff --git a/src/etc/one-context.d/loc-10-network b/src/etc/one-context.d/loc-10-network
--- a/src/etc/one-context.d/loc-10-network
+++ b/src/etc/one-context.d/loc-10-network
@@ -20,7 +20,8 @@
 
 . /etc/one-context.d/loc-10-network.d/functions
 
-action="$1"
+context_type="$1"
+action="$2"
 os_id=$(detect_os)
 
 if [ -z "${action}" ] ; then
@@ -68,6 +69,20 @@ if [ "${NETCFG_TYPE}" != 'none' ] ; then
             break
         fi
     done
+
+    # this is a contextualization guard
+    case "${required_context_type}" in
+        ''|local|online)
+            if [ "${required_context_type:-local}" != "${context_type}" ] ; then
+                # skip this netcfg at this stage
+                exit 0
+            fi
+            ;;
+        *)
+            echo "ERROR [!]: Unknown required context type: ${required_context_type}" >&2
+            exit 1
+            ;;
+    esac
 
     if [ "${_found_valid_netcfg}" = 'no' ] ; then
         echo "ERROR [!]: None of the requested network types is supported on: ${os_id}" >&2
diff --git a/src/etc/one-context.d/loc-10-network.d/netcfg-nm b/src/etc/one-context.d/loc-10-network.d/netcfg-nm
--- a/src/etc/one-context.d/loc-10-network.d/netcfg-nm
+++ b/src/etc/one-context.d/loc-10-network.d/netcfg-nm
@@ -20,6 +20,8 @@
 # network module implementation
 #
 
+export required_context_type=online
+
 is_network_supported()
 {
     command -v nmcli >/dev/null
@@ -29,6 +31,7 @@ is_network_supported()
 
 configure_network()
 {
+    wait_for_nm
     gen_resolvconf
     gen_network_configuration
 }
@@ -77,6 +80,29 @@ export external
 export detach
 export all_nameservers
 export all_search_domains
+
+wait_for_nm()
+{
+    _timeout=30
+    while [ "$_timeout" -gt 0 ] ; do
+        if _nm_networking=$(nmcli networking 2>/dev/null) ; then
+            break
+        fi
+
+        _timeout=$(( _timeout - 1 ))
+        sleep 1
+    done
+
+    if [ "${_timeout}" -eq 0 ] ; then
+        echo "ERROR [!]: NetworkManager is not running" >&2
+        exit 1
+    elif [ "${_nm_networking}" = 'enabled' ] ; then
+        return 0
+    else
+        echo "ERROR [!]: NetworkManager is disabled" >&2
+        exit 1
+    fi
+}
 
 gen_iface_conf()
 {
