F #227: Update loc-10-network WIP
- Change CONTEXT_NETCFG_TYPE to NETCFG_TYPE
- Deduplicate code and refactor
- Add support for DHCP
- Add new netcfg Network Manager
- Start one-contextd *after* Network Manager service (if present)
- Finish one-contexd *before* systemd-networkd (if present)
- Finish one-contexd *before* networking on debian (if present)
- Remove loc-11-dns and instead configure resolv.conf in loc-10-network
- Improve shellcheck compatibility and fix small issues

Signed-off-by: Petr Ospalý <pospaly@opennebula.io>

diff --git a/src/etc/one-context.d/loc-10-network b/src/etc/one-context.d/loc-10-network
--- a/src/etc/one-context.d/loc-10-network
+++ b/src/etc/one-context.d/loc-10-network
@@ -16,44 +16,46 @@
 # limitations under the License.                                             #
 #--------------------------------------------------------------------------- #
 
+# shellcheck disable=SC1091,SC1090
+
 . /etc/one-context.d/loc-10-network.d/functions
 
-ACTION="$1"
-OS_ID=$(detect_os)
+_ACTION="$1"
+_OS_ID=$(detect_os)
 
-if [ -z "${ACTION}" ] ; then
-    ACTION="configure"
+if [ -z "${_ACTION}" ] ; then
+    _ACTION="configure"
 fi
 
-if [ -z "${CONTEXT_NETCFG_TYPE}" ] ; then
-    case "${OS_ID}" in
+if [ -z "${NETCFG_TYPE}" ] ; then
+    case "${_OS_ID}" in
         alpine)
-            CONTEXT_NETCFG_TYPE='interfaces'
+            NETCFG_TYPE='interfaces'
             ;;
         altlinux)
-            CONTEXT_NETCFG_TYPE='networkd'
+            NETCFG_TYPE='networkd'
             ;;
         debian|ubuntu|devuan)
-            CONTEXT_NETCFG_TYPE='interfaces'
+            NETCFG_TYPE='interfaces'
             ;;
         fedora|centos|rhel|almalinux|ol|rocky)
-            CONTEXT_NETCFG_TYPE='scripts'
+            NETCFG_TYPE='scripts'
             ;;
         opensuse*)
-            CONTEXT_NETCFG_TYPE='scripts'
+            NETCFG_TYPE='scripts'
             ;;
         freebsd)
-            CONTEXT_NETCFG_TYPE='bsd'
+            NETCFG_TYPE='bsd'
             ;;
         *)
-            CONTEXT_NETCFG_TYPE='none'
+            NETCFG_TYPE='none'
             ;;
     esac
 fi
 
-if [ "${CONTEXT_NETCFG_TYPE}" != 'none' ] ; then
+if [ "${NETCFG_TYPE}" != 'none' ] ; then
     _found_valid_netcfg='no'
-    for _cfgtype in ${CONTEXT_NETCFG_TYPE} ; do
+    for _cfgtype in ${NETCFG_TYPE} ; do
         if [ -e "/etc/one-context.d/loc-10-network.d/netcfg-${_cfgtype}" ] ; then
             . "/etc/one-context.d/loc-10-network.d/netcfg-${_cfgtype}"
         else
@@ -68,15 +70,15 @@ if [ "${CONTEXT_NETCFG_TYPE}" != 'none' ] ; then
     done
 
     if [ "${_found_valid_netcfg}" = 'no' ] ; then
-        echo "ERROR [!]: None of the requested network types is supported on: ${OS_ID}" >&2
+        echo "ERROR [!]: None of the requested network types is supported on: ${_OS_ID}" >&2
         exit 1
     fi
 else
     # any action is meaningless without functioning network type
-    ACTION='none'
+    _ACTION='none'
 fi
 
-case "$ACTION" in
+case "$_ACTION" in
     none)
         echo "INFO: Network will not be configured" >&2
         ;;
@@ -88,7 +90,7 @@ case "$ACTION" in
         reload_network
         ;;
     *)
-        echo "ERROR [!]: Unknown ACTION: ${ACTION}" >&2
+        echo "ERROR [!]: Unknown ACTION: ${_ACTION}" >&2
         exit 1
         ;;
 esac
diff --git a/src/etc/one-context.d/loc-10-network.d/functions b/src/etc/one-context.d/loc-10-network.d/functions
--- a/src/etc/one-context.d/loc-10-network.d/functions
+++ b/src/etc/one-context.d/loc-10-network.d/functions
@@ -16,6 +16,8 @@
 # limitations under the License.                                             #
 #--------------------------------------------------------------------------- #
 
+# shellcheck disable=SC2155
+
 #
 # network module interface
 #
@@ -27,31 +29,45 @@ is_network_supported()
 
 configure_network()
 {
-    echo "ERROR [!]: No 'configure_network' implementation for the network type: ${CONTEXT_NETCFG_TYPE}" >&2
+    echo "ERROR [!]: No 'configure_network' implementation for the network type: ${NETCFG_TYPE}" >&2
     exit 1
 }
 
 stop_network()
 {
-    echo "ERROR [!]: No 'stop_network' implementation for the network type: ${CONTEXT_NETCFG_TYPE}" >&2
+    echo "ERROR [!]: No 'stop_network' implementation for the network type: ${NETCFG_TYPE}" >&2
     exit 1
 }
 
 start_network()
 {
-    echo "ERROR [!]: No 'start_network' implementation for the network type: ${CONTEXT_NETCFG_TYPE}" >&2
+    echo "ERROR [!]: No 'start_network' implementation for the network type: ${NETCFG_TYPE}" >&2
     exit 1
 }
 
 reload_network()
 {
-    echo "ERROR [!]: No 'reload_network' implementation for the network type: ${CONTEXT_NETCFG_TYPE}" >&2
+    echo "ERROR [!]: No 'reload_network' implementation for the network type: ${NETCFG_TYPE}" >&2
     exit 1
 }
 
 #
 # generic shared functions
 #
+
+is_true()
+(
+    _value=$(eval echo "\$${1}" | \
+        sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | \
+        tr '[:upper:]' '[:lower:]')
+    case "$_value" in
+        1|true|yes|y)
+            return 0
+            ;;
+    esac
+
+    return 1
+)
 
 # return OS ID
 detect_os()
@@ -65,6 +81,18 @@ detect_os()
         uname | tr '[:upper:]' '[:lower:]'
     fi
 )
+
+skip_interface()
+{
+    [ -z "${_DEV}" ] && return 0
+
+    is_true "${_DHCP}" && return 1
+    is_true "${_DHCP6}" && return 1
+
+    [ -z "${_IP}${_IP6}" ] && return 0
+
+    return 1
+}
 
 # args: <iface> <name>
 get_iface_var()
@@ -183,12 +211,12 @@ get_interface_alias()
 
 get_context_interfaces()
 (
-    env | grep -E "^ETH[0-9]+_MAC=" | sed 's/_.*$//' | sort
+    env | sed -n 's/^\(ETH[0-9]\+\)_MAC=.*/\1/p' | sort
 )
 
 get_pci_interfaces()
 (
-    env | grep -E "^PCI[0-9]+_MAC=" | sed 's/_.*$//' | sort
+    env | sed -n 's/^\(PCI[0-9]\+\)_MAC=.*/\1/p' | sort
 )
 
 get_interface_mac()
@@ -204,3 +232,103 @@ get_dev()
     echo "$list" | grep "$mac" | cut -d' ' -f1 | tail -n1
 )
 
+# arg: <interface/alias>
+setup_ipadr_vars()
+{
+    export _IP=$(get_ip "$1")
+    export _NETWORK=$(get_network "$1")
+    export _MASK=$(get_mask "$1")
+    export _CIDR=$(mask2cidr "$_MASK")
+    export _DHCP=$(get_iface_var "$1" "DHCP")
+}
+
+# arg: <interface/alias>
+setup_ip6adr_vars()
+{
+    export _IP6=$(get_iface_var "$1" "IP6")
+    export _IP6_PREFIX_LENGTH=$(get_iface_var "$1" "IP6_PREFIX_LENGTH")
+    export _IP6_ULA=$(get_iface_var "$1" "IP6_ULA")
+    export _DHCP6=$(get_iface_var "$1" "DHCP6")
+
+    [ -z "$_IP6" ] && _IP6=$(get_iface_var "$1" "IPV6")
+    [ -z "$_IP6_PREFIX_LENGTH" ] && _IP6_PREFIX_LENGTH=64
+}
+
+# arg: <interface>
+setup_iface_vars()
+{
+    _iface_mac=$(get_interface_mac)
+
+    export _MAC=$(get_iface_var "$1" "MAC")
+    export _DEV=$(get_dev "$_iface_mac" "$_MAC")
+    export _MTU=$(get_mtu "$1")
+    export _GATEWAY=$(get_gateway "$1")
+    export _METRIC=$(get_iface_var "$1" "METRIC")
+    export _DNS=$(get_dns "$1")
+    export _SEARCH_DOMAIN=$(get_search_domain "$1")
+    export _GATEWAY6=$(get_gateway6 "$1")
+
+    setup_ipadr_vars "$1"
+    setup_ip6adr_vars "$1"
+}
+
+# arg: <alias>
+setup_alias_vars()
+{
+    export _EXTERNAL=$(get_iface_var "$1" "EXTERNAL")
+    export _DETACH=$(get_iface_var "$1" "DETACH")
+}
+
+get_nameservers()
+(
+    _dns_variables=$(env | sed -n 's/^\(ETH[0-9]\+_DNS\)=.*/\1/p' | sort)
+
+    for _dns in DNS ${_dns_variables} ; do
+        _value=$(eval "echo \"\${$_dns}\"")
+        if [ -n "$_value" ] ; then
+            echo "$_value"
+        fi
+    done
+)
+
+get_searchdomains()
+(
+    _search_domains=$(env | sed -n 's/^\(ETH[0-9]\+_SEARCH_DOMAIN\)=.*/\1/p' | sort)
+
+    for _search in SEARCH_DOMAIN ${_search_domains} ; do
+        _value=$(eval "echo \"\${$_search}\"")
+        if [ -n "$_value" ] ; then
+            echo "$_value"
+        fi
+    done
+)
+
+gen_resolvconf()
+{
+    export _NAMESERVERS=$(get_nameservers)
+    export _SEARCH_DOMAINS=$(get_searchdomains)
+
+    [ -z "$_NAMESERVERS" ] && return 0
+
+    if [ -L /etc/resolv.conf ]; then
+        unlink /etc/resolv.conf
+    else
+        cat /dev/null > /etc/resolv.conf
+    fi
+
+    for _nameserver in $_NAMESERVERS ; do
+        echo "nameserver ${_nameserver}" >> /etc/resolv.conf
+    done
+
+    if [ -f /etc/sysconfig/network/config ]; then
+        sed -i "/^NETCONFIG_DNS_STATIC_SERVERS=/ s/=.*$/=\"${_NAMESERVERS}\"/" /etc/sysconfig/network/config
+    fi
+
+    [ -z "$_SEARCH_DOMAINS" ] && return 0
+
+    echo "search ${_SEARCH_DOMAINS}" >> /etc/resolv.conf
+
+    if [ -f /etc/sysconfig/network/config ]; then
+        sed -i "/^NETCONFIG_DNS_STATIC_SEARCHLIST=/ s/=.*$/=\"${_SEARCH_DOMAINS}\"/" /etc/sysconfig/network/config
+    fi
+}
