F #227: Refactor loc-10-network
* F #227: Update network context

- Rework support for DHCP and DHCP6
- Support new context ETH?_METHOD and ETH?_IP6_METHOD
- Add new loc-10-network netcfg interface: initialize_network
- Wipe out stale netcfg configs to avoid conflicts
- Add reference links for some workarounds
- Fix shellcheck

Signed-off-by: Petr Ospalý <pospaly@opennebula.io>

* F #227: Let networkd to use default for IPv6

Signed-off-by: Petr Ospalý <pospaly@opennebula.io>

* F #227: Improve cleanup in initialize_network

Signed-off-by: Petr Ospalý <pospaly@opennebula.io>

* F #227: Fix Network Manager reconfiguration

Signed-off-by: Petr Ospalý <pospaly@opennebula.io>

* M #-: Update systemd service descriptions

* F #227: Adapt FreeBSD, support live reconfiguration

* B #239: Use systemctl --no-block in udev on Debian-like

* F #227: Fix unmanaged-devices with NM on ubuntu

Instead of touching 10-globally-managed-devices.conf during netcfg-nm
script we are shipping the file as part of the package. The reason is
that this file must be in place *BEFORE* Network Manager daemon is
started and reload is not sufficiant (read: it does not work). Other
option would be to restarting NM instead of reloading but that would
ifup/down all interfaces which is not a desired behavior especially if
those are in use (recontextualization).

Signed-off-by: Petr Ospalý <pospaly@opennebula.io>

* F #227: Improve cleanup for NM

Signed-off-by: Petr Ospalý <pospaly@opennebula.io>

* F #227: Fix initialize_network usage and cleanup

Signed-off-by: Petr Ospalý <pospaly@opennebula.io>

* F #227: Workaround FreeBSD emul. NIC attach, manage rtsold

* F #227: Fix is_true argument usage

Signed-off-by: Petr Ospalý <pospaly@opennebula.io>

* F #227: Improve NM reconfigure

Signed-off-by: Petr Ospalý <pospaly@opennebula.io>

* F #227: Fix NM and networkd reconfiguration

Signed-off-by: Petr Ospalý <pospaly@opennebula.io>

* F #227: Fix netplan's issue with empty stanzas

Signed-off-by: Petr Ospalý <pospaly@opennebula.io>

* B #239: Use abs. path /bin/systemctl in Debian-like udev

Closes #239

Co-authored-by: Vlastimil Holer <vholer@opennebula.io>

diff --git a/src/etc/one-context.d/loc-10-network b/src/etc/one-context.d/loc-10-network
--- a/src/etc/one-context.d/loc-10-network
+++ b/src/etc/one-context.d/loc-10-network
@@ -70,20 +70,6 @@ if [ "${NETCFG_TYPE}" != 'none' ] ; then
         fi
     done
 
-    # this is a contextualization guard
-    case "${required_context_type}" in
-        ''|local|online)
-            if [ "${required_context_type:-local}" != "${context_type}" ] ; then
-                # skip this netcfg at this stage
-                exit 0
-            fi
-            ;;
-        *)
-            echo "ERROR [!]: Unknown required context type: ${required_context_type}" >&2
-            exit 1
-            ;;
-    esac
-
     if [ "${_found_valid_netcfg}" = 'no' ] ; then
         echo "ERROR [!]: None of the requested network types is supported on: ${os_id}" >&2
         exit 1
@@ -92,6 +78,38 @@ else
     # any action is meaningless without functioning network type
     action='none'
 fi
+
+# regardless of the required_context_type we need cleanup in the 'local' stage
+#
+# TODO: currently we must skip cleanup during reconfigure action (check-out the
+# initialize_network function) otherwise we would wiped-out running config and
+# broke the system
+if [ "${context_type}" = 'local' ] ; then
+    case "$action" in
+        configure|reconfigure)
+            initialize_network
+            ;;
+        *)
+            echo "ERROR [!]: Unknown ACTION: ${action}" >&2
+            exit 1
+            ;;
+    esac
+fi
+
+# this is a contextualization guard
+# shellcheck disable=SC2154
+case "${required_context_type}" in
+    ''|local|online)
+        if [ "${required_context_type:-local}" != "${context_type}" ] ; then
+            # skip this netcfg at this stage
+            exit 0
+        fi
+        ;;
+    *)
+        echo "ERROR [!]: Unknown required context type: ${required_context_type}" >&2
+        exit 1
+        ;;
+esac
 
 case "$action" in
     none)
diff --git a/src/etc/one-context.d/loc-10-network.d/functions b/src/etc/one-context.d/loc-10-network.d/functions
--- a/src/etc/one-context.d/loc-10-network.d/functions
+++ b/src/etc/one-context.d/loc-10-network.d/functions
@@ -29,6 +29,67 @@ is_network_supported()
     false
 }
 
+initialize_network()
+{
+    # shellcheck disable=SC2154
+    case "${os_id}" in
+        freebsd)
+            :
+            ;;
+        *)
+            mkdir -p /etc/sysctl.d/
+            rm -f /etc/sysctl.d/00-opennebula-netcfg.conf
+            sysctl -p
+            ;;
+    esac
+
+    #
+    # remove all stale configs from any of the previous runs
+    #
+
+    # TODO: improve this and support proper network unconfigure and cleanup
+    # on action=reconfigure too - this becomes problematic when NETCFG_TYPE is
+    # changed while VM is running (deleting configs will break ifdown etc.)
+    #
+    # shellcheck disable=SC2154
+    [ "${action}" = 'configure' ] || return 0
+
+    _context_interfaces=$(get_context_interfaces)
+    _iface_mac=$(get_interface_mac)
+
+    for _iface in $_context_interfaces; do
+        _mac=$(get_iface_var "${_iface}" "MAC")
+        _dev=$(get_dev "${_iface_mac}" "${_mac}")
+
+        # network-scripts
+        rm -f \
+            "/etc/sysconfig/network-scripts/route-${dev}" \
+            "/etc/sysconfig/network/ifroute-${dev}" \
+            "/etc/sysconfig/network/ifsysctl-${dev}" \
+            "/etc/sysconfig/network-scripts/ifcfg-${dev}" \
+            "/etc/sysconfig/network/ifcfg-${dev}" \
+            ;
+
+        # networkd
+        rm -f "/etc/systemd/network/${dev}.network"
+
+        # nm (on RH systems it was deleted with ifcfg-*)
+        for _nm_con in /etc/NetworkManager/system-connections/* ; do
+            if [ -e "${_nm_con}" ] && grep -q "^interface-name=${_dev}$" "${_nm_con}" ; then
+                rm -f "${_nm_con}"
+            fi
+        done
+    done
+
+    # interfaces
+    if [ -e /etc/network/interfaces ] ; then
+        cat /dev/null > /etc/network/interfaces
+    fi
+
+    # netplan
+    rm -f /etc/netplan/00-opennebula-generated-network.yaml
+}
+
 configure_network()
 {
     echo "ERROR [!]: No 'configure_network' implementation for the network type: ${NETCFG_TYPE}" >&2
@@ -57,9 +118,10 @@ reload_network()
 # generic shared functions
 #
 
+# arg: <true|yes|false|no>
 is_true()
 (
-    _value=$(eval echo "\$${1}" | \
+    _value=$(echo "$1" | \
         sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | \
         tr '[:upper:]' '[:lower:]')
     case "$_value" in
@@ -84,14 +146,79 @@ detect_os()
     fi
 )
 
+# arg: <iface>
+disable_ipv6()
+(
+    # shellcheck disable=SC2154
+    case "${os_id}" in
+        freebsd)
+            # TODO: these are the relevant options in /etc/rc.conf:
+            #   ip6addrctl_enable="NO"
+            #   ip6addrctl_policy="ipv4_prefer"
+            #   ipv6_activate_all_interfaces="NO"
+            #   ipv6_network_interfaces="none"
+            echo "ERROR [!]: Disabling of IPv6 on '${os_id}' is not supported" >&2
+            ;;
+        *)
+            echo "net.ipv6.conf.${1}.disable_ipv6 = 1" >> /etc/sysctl.d/00-opennebula-netcfg.conf
+            sysctl -w "net.ipv6.conf.${1}.disable_ipv6=1"
+            ;;
+    esac
+)
+
 skip_interface()
 {
     [ -z "${dev}" ] && return 0
 
-    is_true "${dhcp}" && return 1
-    is_true "${dhcp6}" && return 1
+    _skip4=
+    case "${method}" in
+        ''|static)
+            if [ -z "${ip}" ] ; then
+                _skip4=yes
+            else
+                _skip4=no
+            fi
+            ;;
+        skip)
+            _skip4=yes
+            ;;
+        dhcp)
+            _skip4=no
+            ;;
+        *)
+            echo "ERROR [!]: Unknown IPv4 method: ${method}" >&2
+            exit 1
+            ;;
+    esac
 
-    [ -z "${ip}${ip6}" ] && return 0
+    _skip6=
+    case "${method6}" in
+        ''|static)
+            if [ -z "${ip6}" ] ; then
+                _skip6=yes
+            else
+                _skip6=no
+            fi
+            ;;
+        skip)
+            _skip6=yes
+            ;;
+        disabled)
+            disable_ipv6 "${dev}"
+            _skip6=yes
+            ;;
+        auto|dhcp)
+            _skip6=no
+            ;;
+        *)
+            echo "ERROR [!]: Unknown IPv4 method: ${method6}" >&2
+            exit 1
+            ;;
+    esac
+
+    if is_true "${_skip4}" && is_true "${_skip6}" ; then
+        return 0
+    fi
 
     return 1
 }
@@ -244,7 +371,6 @@ setup_ipadr_vars()
     export network=$(get_network "$1")
     export mask=$(get_mask "$1")
     export cidr=$(mask2cidr "$mask")
-    export dhcp=$(get_iface_var "$1" "DHCP")
 }
 
 # arg: <interface/alias>
@@ -253,7 +379,6 @@ setup_ip6adr_vars()
     export ip6=$(get_iface_var "$1" "IP6")
     export ip6_prefix_length=$(get_iface_var "$1" "IP6_PREFIX_LENGTH")
     export ip6_ula=$(get_iface_var "$1" "IP6_ULA")
-    export dhcp6=$(get_iface_var "$1" "DHCP6")
 
     [ -z "$ip6" ] && ip6=$(get_iface_var "$1" "IPV6")
     [ -z "$ip6_prefix_length" ] && ip6_prefix_length=64
@@ -268,10 +393,12 @@ setup_iface_vars()
     export dev=$(get_dev "$_iface_mac" "$mac")
     export mtu=$(get_mtu "$1")
     export gateway=$(get_gateway "$1")
+    export gateway6=$(get_gateway6 "$1")
     export metric=$(get_iface_var "$1" "METRIC")
     export dns=$(get_dns "$1")
     export search_domains=$(get_search_domain "$1")
-    export gateway6=$(get_gateway6 "$1")
+    export method=$(get_iface_var "$1" "METHOD")
+    export method6=$(get_iface_var "$1" "IP6_METHOD")
 
     setup_ipadr_vars "$1"
     setup_ip6adr_vars "$1"
