F #227: WIP

diff --git a/src/etc/one-context.d/loc-10-network.d/functions b/src/etc/one-context.d/loc-10-network.d/functions
--- a/src/etc/one-context.d/loc-10-network.d/functions
+++ b/src/etc/one-context.d/loc-10-network.d/functions
@@ -117,9 +117,15 @@ EOT
 
 nm_disable() {
     if [ -d /etc/NetworkManager/conf.d/ ] &&
-       ! [ -e /etc/NetworkManager/conf.d/50-one-context.conf ];
+       ! [ -e /etc/NetworkManager/conf.d/50-unmanaged-devices.conf ];
     then
-        cat - <<EOF >/etc/NetworkManager/conf.d/50-one-context.conf
+        cat - <<EOF >/etc/NetworkManager/conf.d/50-unmanaged-devices.conf
+# Generated by one-context
+
+# NOTE: NetworkManager was dynamically disabled by OpenNebula
+# contextualization scripts because interfaces are managed by
+# different network service!
+
 [keyfile]
 unmanaged-devices=*
 EOF
@@ -133,8 +139,8 @@ EOF
 }
 
 nm_enable() {
-    if [ -e /etc/NetworkManager/conf.d/50-one-context.conf ]; then
-        rm -f /etc/NetworkManager/conf.d/50-one-context.conf
+    if [ -e /etc/NetworkManager/conf.d/50-unmanaged-devices.conf ]; then
+        rm -f /etc/NetworkManager/conf.d/50-unmanaged-devices.conf
 
         if command -v systemctl >/dev/null; then
             systemctl --no-block try-reload-or-restart NetworkManager.service 2>/dev/null
@@ -166,11 +172,6 @@ reload_network()
 {
     echo "ERROR [!]: No 'reload_network' implementation for the network type: ${NETCFG_TYPE}" >&2
     exit 1
-}
-
-wait_online()
-{
-    return
 }
 
 #
@@ -293,7 +294,7 @@ skip_interface()
     esac
 
     _skip6=
-    case "${method6}" in
+    case "${ip6_method}" in
         ''|static)
             if [ -z "${ip6}" ] ; then
                 _skip6=yes
@@ -312,7 +313,7 @@ skip_interface()
             _skip6=no
             ;;
         *)
-            echo "ERROR [!]: Unknown IPv6 method: ${method6}" >&2
+            echo "ERROR [!]: Unknown IPv6 method: ${ip6_method}" >&2
             _skip6=yes
             ;;
     esac
@@ -498,16 +499,16 @@ setup_iface_vars()
     export gateway=$(get_gateway "$1")
     export gateway6=$(get_gateway6 "$1")
     export metric=$(get_iface_var "$1" "METRIC")
-    export metric6=$(get_iface_var "$1" "METRIC6")
+    export ip6_metric=$(get_iface_var "$1" "IP6_METRIC")
     export dns=$(get_dns "$1")
     export search_domains=$(get_search_domain "$1")
     export method=$(get_iface_var "$1" "METHOD")
-    export method6=$(get_iface_var "$1" "IP6_METHOD")
+    export ip6_method=$(get_iface_var "$1" "IP6_METHOD")
 
     # defaults
-    [ -z "$metric6" ] && metric6="${metric}"
-    [ -z "$method"  ] && method='static'
-    [ -z "$method6" ] && method6="${method}"
+    [ -z "$ip6_metric" ] && ip6_metric="${metric}"
+    [ -z "$method"  ]    && method='static'
+    [ -z "$ip6_method" ] && ip6_method="${method}"
 
     setup_ipadr_vars "$1"
     setup_ip6adr_vars "$1"
