F #227: WIP

diff --git a/src/etc/one-context.d/loc-10-network.d/functions b/src/etc/one-context.d/loc-10-network.d/functions
--- a/src/etc/one-context.d/loc-10-network.d/functions
+++ b/src/etc/one-context.d/loc-10-network.d/functions
@@ -29,7 +29,6 @@ is_network_supported()
     false
 }
 
-# VH-TODO: ideally this should be split across all individual netcfg renderers
 initialize_network()
 {
     # shellcheck disable=SC2154
@@ -39,9 +38,7 @@ initialize_network()
             ;;
         *)
             mkdir -p /etc/sysctl.d/
-            # VH-TODO: 00-one-context.conf?
-            rm -f /etc/sysctl.d/00-opennebula-netcfg.conf
-            # VH-TODO: is this necessary?
+            rm -f /etc/sysctl.d/50-one-context.conf
             sysctl --system 2>/dev/null || sysctl -p
             ;;
     esac
@@ -67,14 +64,17 @@ initialize_network()
         # network-scripts
         rm -f \
             "/etc/sysconfig/network-scripts/route-${dev}" \
+            "/etc/sysconfig/network-scripts/route6-${dev}" \
+            "/etc/sysconfig/network-scripts/ifcfg-${dev}" \
             "/etc/sysconfig/network/ifroute-${dev}" \
             "/etc/sysconfig/network/ifsysctl-${dev}" \
-            "/etc/sysconfig/network-scripts/ifcfg-${dev}" \
             "/etc/sysconfig/network/ifcfg-${dev}" \
             ;
 
         # networkd
-        rm -f "/etc/systemd/network/${dev}.network"
+        rm -f \
+            "/etc/systemd/network/${dev}.network" \
+            "/etc/systemd/network/${dev}.link"
 
         # nm (on RH systems it was deleted with ifcfg-*)
         for _nm_con in /etc/NetworkManager/system-connections/* ; do
@@ -84,22 +84,42 @@ initialize_network()
         done
     done
 
+    # To avoid clashes when running legacy network-scripts and
+    # NetworkManager/networkd, we disable old-style networking
+    # on Red Hats and enable later back only if needed.
+    if [ -d /etc/sysconfig/network-scripts/ ]; then
+        touch /etc/sysconfig/network
+        sed -i -e '/^NETWORKING=/d' /etc/sysconfig/network
+        echo 'NETWORKING=no' >>/etc/sysconfig/network
+    fi
+
     # interfaces
     if [ -e /etc/network/interfaces ] ; then
-        # VH-TODO: lo
-        cat /dev/null > /etc/network/interfaces
+        cat <<EOT >/etc/network/interfaces
+# Generated by one-context
+auto lo
+iface lo inet loopback
+
+EOT
+
+        case "${os_id}" in
+            debian|ubuntu|devuan)
+                echo "source /etc/network/interfaces.d/*.cfg" >> /etc/network/interfaces
+                ;;
+        esac
     fi
 
     # netplan
-    # VH-TODO: 50-one-context.yaml?
-    rm -f /etc/netplan/00-opennebula-generated-network.yaml
+    rm -f /etc/netplan/50-one-context.yaml
 
     nm_disable
 }
 
 nm_disable() {
-    if [ -d /etc/NetworkManager/conf.d/ ] && ! [ -e /etc/NetworkManager/conf.d/50-one-context-unmanaged.conf ]; then
-        cat - <<EOF >/etc/NetworkManager/conf.d/50-one-context-unmanaged.conf
+    if [ -d /etc/NetworkManager/conf.d/ ] &&
+       ! [ -e /etc/NetworkManager/conf.d/50-one-context.conf ];
+    then
+        cat - <<EOF >/etc/NetworkManager/conf.d/50-one-context.conf
 [keyfile]
 unmanaged-devices=*
 EOF
@@ -113,8 +133,8 @@ EOF
 }
 
 nm_enable() {
-    if [ -e /etc/NetworkManager/conf.d/50-one-context-unmanaged.conf ]; then
-        rm -f /etc/NetworkManager/conf.d/50-one-context-unmanaged.conf
+    if [ -e /etc/NetworkManager/conf.d/50-one-context.conf ]; then
+        rm -f /etc/NetworkManager/conf.d/50-one-context.conf
 
         if command -v systemctl >/dev/null; then
             systemctl --no-block try-reload-or-restart NetworkManager.service 2>/dev/null
@@ -148,10 +168,14 @@ reload_network()
     exit 1
 }
 
+wait_online()
+{
+    return
+}
+
 #
 # generic shared functions
 #
-# VH-TODO: Reduce use of functions running in subshell ()
 
 # arg: <true|yes|false|no>
 is_true()
@@ -176,6 +200,14 @@ detect_os()
         # shellcheck disable=SC1091
         . /etc/os-release
         echo "$ID" | tr '[:upper:]' '[:lower:]'
+
+    # check for legacy RHEL/CentOS 6
+    elif [ -f /etc/centos-release ]; then
+        echo 'centos'
+    elif [ -f /etc/redhat-release ]; then
+        echo 'redhat'
+
+    # fallback to uname (returns Linux, FreeBSD, ...)
     else
         uname | tr '[:upper:]' '[:lower:]'
     fi
@@ -196,13 +228,39 @@ disable_ipv6()
             ;;
         *)
             # VH-TODO: do we suport runtime enable?
-            # VH-TODO: align name
             for S in \
                 "net.ipv6.conf.${1}.disable_ipv6=1" \
                 "net.ipv6.conf.${1}.autoconf=0" \
                 "net.ipv6.conf.${1}.accept_ra=0";
             do
-                echo "${S}" >> /etc/sysctl.d/00-opennebula-netcfg.conf
+                # don't duplicate entries on recontextualization
+                if ! grep -Fxq "${S}" /etc/sysctl.d/50-one-context.conf 2>/dev/null; then
+                    echo "${S}" >> /etc/sysctl.d/50-one-context.conf
+                fi
+
+                sysctl -w "${S}" >/dev/null
+            done
+            ;;
+    esac
+)
+
+# arg: <iface>
+disable_ipv6_privacy()
+(
+    case "${os_id}" in
+        freebsd)
+            echo "ERROR [!]: Disabling of IPv6 privacy on '${os_id}' is not supported" >&2
+            ;;
+        *)
+            # shellcheck disable=SC2066
+            for S in \
+                "net.ipv6.conf.${1}.use_tempaddr=0";
+            do
+                # don't duplicate entries on recontextualization
+                if ! grep -Fxq "${S}" /etc/sysctl.d/50-one-context.conf 2>/dev/null; then
+                    echo "${S}" >> /etc/sysctl.d/50-one-context.conf
+                fi
+
                 sysctl -w "${S}" >/dev/null
             done
             ;;
@@ -229,9 +287,8 @@ skip_interface()
             _skip4=no
             ;;
         *)
-            echo "ERROR [!]: Unknown IPv4 method: ${method}" >&2
-            # VH-TODO: This and below exit may leave network completely unconfigured if eth0 is invalid?
-            exit 1
+            echo "ERROR [!]: Unknown IPv4 method: ${method}, skipping" >&2
+            _skip4=yes
             ;;
     esac
 
@@ -255,8 +312,8 @@ skip_interface()
             _skip6=no
             ;;
         *)
-            echo "ERROR [!]: Unknown IPv4 method: ${method6}" >&2
-            exit 1
+            echo "ERROR [!]: Unknown IPv6 method: ${method6}" >&2
+            _skip6=yes
             ;;
     esac
 
@@ -340,6 +397,7 @@ get_mask()
 # arg: <iface>
 get_mtu()
 (
+    # VH_TODO: drop default 1500, nekde se spoleha na tento default!
     _mtu=$(get_iface_var "$1" "MTU")
     echo "${_mtu:-1500}"
 )
@@ -435,14 +493,21 @@ setup_iface_vars()
 
     export mac=$(get_iface_var "$1" "MAC")
     export dev=$(get_dev "$_iface_mac" "$mac")
-    export mtu=$(get_mtu "$1")
+    #export mtu=$(get_mtu "$1")
+    export mtu=$(get_iface_var "$1" "MTU")
     export gateway=$(get_gateway "$1")
     export gateway6=$(get_gateway6 "$1")
     export metric=$(get_iface_var "$1" "METRIC")
+    export metric6=$(get_iface_var "$1" "METRIC6")
     export dns=$(get_dns "$1")
     export search_domains=$(get_search_domain "$1")
     export method=$(get_iface_var "$1" "METHOD")
     export method6=$(get_iface_var "$1" "IP6_METHOD")
+
+    # defaults
+    [ -z "$metric6" ] && metric6="${metric}"
+    [ -z "$method"  ] && method='static'
+    [ -z "$method6" ] && method6="${method}"
 
     setup_ipadr_vars "$1"
     setup_ip6adr_vars "$1"
diff --git a/src/etc/one-context.d/loc-10-network.d/netcfg-netplan b/src/etc/one-context.d/loc-10-network.d/netcfg-netplan
--- a/src/etc/one-context.d/loc-10-network.d/netcfg-netplan
+++ b/src/etc/one-context.d/loc-10-network.d/netcfg-netplan
@@ -30,9 +30,18 @@ is_network_supported()
 configure_network()
 {
     gen_resolvconf
-    gen_network_configuration > /etc/netplan/00-opennebula-generated-network.yaml
+    gen_network_configuration > /etc/netplan/50-one-context.yaml
     netplan generate
     nm_symlink_run_connections
+
+    # On Debian 10, Ubuntu 18.04 the initial netplan apply is needed to set some
+    # interface parameters (e.g., MTU). Unfortunately, this deadlocks booting
+    # of current systems, so we execute netplan apply on the background.
+    case "${NETCFG_NETPLAN_RENDERER}" in
+        ''|networkd)
+            nohup netplan apply &>/dev/null &
+            ;;
+    esac
 }
 
 stop_network()
@@ -42,9 +51,8 @@ stop_network()
 
 start_network()
 {
-    # VH-TODO: maybe generate >> networking start >> apply?
-    service networking start
     netplan generate
+    service networking start
     nm_symlink_run_connections
     netplan apply
 }
@@ -54,6 +62,37 @@ reload_network()
     netplan generate
     nm_symlink_run_connections
     netplan apply
+}
+
+wait_online()
+{
+    case "${NETCFG_NETPLAN_RENDERER}" in
+        networkd)
+            # Dummy query waits until networkd is running
+            networkctl list &>/dev/null
+
+            if [ -x /lib/systemd/systemd-networkd-wait-online ]; then
+                /lib/systemd/systemd-networkd-wait-online --timeout=15 &>/dev/null
+            fi
+
+            # Safety loop to wait until all interfaces are configured
+            _timeout=15
+            while [ "$_timeout" -gt 0 ]; do
+                # we do ignore successful/failed states
+                if ! networkctl list --no-legend | grep -Eqiv 'unmanaged|configured|failed|linger'; then
+                    break
+                fi
+
+                _timeout=$(( _timeout - 1 ))
+                sleep 1
+            done
+            ;;
+        NetworkManager)
+            if command -v nm-online >/dev/null; then
+                nm-online -q -t 30
+            fi
+            ;;
+    esac
 }
 
 #
@@ -79,6 +118,7 @@ export gateway6
 export method
 export method6
 export metric
+export metric6
 export dns
 export search_domains
 export external
@@ -118,25 +158,35 @@ gen_addresses()
 
 gen_routes()
 {
-    if [ -n "${gateway}" ] ; then
+    if [ -n "${gateway}" ] && { [ -z "${method}" ] || [ "${method}" = 'static' ]; }; then
         cat <<EOT
         - to: "0.0.0.0/0"
           via: ${gateway}
 EOT
+
+        # Force default Linux IPv4 metric (man 8 route) to override
+        # automatic metrics calculation done by NetworkManager and unify
+        # behavior among different renderers.
+        metric=${metric:-0}
 
         if [ -n "${metric}" ] ; then
             echo "          metric: ${metric}"
         fi
     fi
 
-    if [ -n "${gateway6}" ] ; then
+    if [ -n "${gateway6}" ] && { [ -z "${method6}" ] || [ "${method6}" = 'static' ]; }; then
         cat <<EOT
         - to: "::/0"
           via: ${gateway6}
 EOT
 
-        if [ -n "${metric}" ] ; then
-            echo "          metric: ${metric}"
+        # Force default Linux IPv6 metric (man 8 route) to override
+        # automatic metrics calculation done by NetworkManager and unify
+        # behavior among different renderers.
+        metric6=${metric6:-1}
+
+        if [ -n "${metric6}" ] ; then
+            echo "          metric: ${metric6}"
         fi
     fi
 }
@@ -176,7 +226,6 @@ EOT
 EOT
     fi
 
-    # VH-TODO: support configurable privacy
     cat <<EOT
       ipv6-privacy: false
 EOT
@@ -195,20 +244,15 @@ EOT
 # we symlink the connection files into /etc
 nm_symlink_run_connections()
 {
-    if [ -n "${NETCFG_NETPLAN_RENDERER}" ] && \
-       [ "${NETCFG_NETPLAN_RENDERER}" != 'NetworkManager' ];
+    if [ "${NETCFG_NETPLAN_RENDERER}" != 'NetworkManager' ] ||
+       ! [ -d /run/NetworkManager/system-connections ];
     then
         return
     fi
 
-    if ! [ -d /run/NetworkManager/system-connections ]; then
-        return
-    fi
-
     # cleanup any old symlinks
-    rm -f /etc/NetworkManager/system-connections/netplan-eth*
+    rm -f /etc/NetworkManager/system-connections/netplan-*
 
-    # VH-TODO: Simplify test only for Debian 10
     case "$(NetworkManager --version 2>/dev/null)" in
         1.14.*) # Debian 10
             echo "WARNING: Symlinking NM's ephemeral connections into /etc" >&2
@@ -218,10 +262,12 @@ nm_symlink_run_connections()
             ;;
     esac
 
-    # symlink any Netplan connection files
-    for SRC in /run/NetworkManager/system-connections/netplan-eth*; do
-        DST="/etc/NetworkManager/system-connections/$(basename "${SRC}")"
-        ln -s "${SRC}" "${DST}"
+    # symlink Netplan connection files
+    for _src in /run/NetworkManager/system-connections/netplan-*; do
+        if [ -f "${_src}" ]; then
+            _dst="/etc/NetworkManager/system-connections/$(basename "${_src}")"
+            ln -s "${_src}" "${_dst}"
+        fi
     done
 }
 
@@ -244,9 +290,6 @@ gen_network_configuration()
         nm_enable
     fi
 
-    # TODO: consider to change the default to more robust NetworkManager - the
-    # netplan's renderer default is networkd which may encounter issues with
-    # version 248
     cat <<EOT
 # Generated by one-context
 network:
diff --git a/src/etc/one-context.d/loc-10-network.d/netcfg-networkd b/src/etc/one-context.d/loc-10-network.d/netcfg-networkd
--- a/src/etc/one-context.d/loc-10-network.d/netcfg-networkd
+++ b/src/etc/one-context.d/loc-10-network.d/netcfg-networkd
@@ -43,30 +43,41 @@ start_network()
     systemctl start systemd-networkd.service
 
     # Dummy query waits until networkd is running
-    networkctl list >/dev/null
+    networkctl list &>/dev/null || :
 }
 
 reload_network()
 {
-    # VH-TODO: networkctl reload && networkctl reconfigure ethX
+    # TODO: for newer systemd-networkd use
+    # networkctl reload && networkctl reconfigure ethX
+    # and fallback to service restart only if needed
     systemctl restart systemd-networkd.service
 
     # Dummy query waits until networkd is running
-    networkctl list >/dev/null
+    networkctl list &>/dev/null || :
 }
 
-# # VH-TODO: deosn't have to be 100% reliable
-# wait_online()
-# {
-#     # Dummy query waits until networkd is running
-#     networkctl list >/dev/null
-#
-#     if [ -x /lib/systemd/systemd-networkd-wait-online ]; then
-#         /lib/systemd/systemd-networkd-wait-online --timeout=30
-#     else
-#         echo "ERROR [!]: Can't wait for online state, systemd-networkd-wait-online not found" >&2
-#     fi
-# }
+wait_online()
+{
+    # Dummy query waits until networkd is running
+    networkctl list &>/dev/null || :
+
+    if [ -x /lib/systemd/systemd-networkd-wait-online ]; then
+        /lib/systemd/systemd-networkd-wait-online --timeout=15 &>/dev/null
+    fi
+
+    # Safety loop to wait until all interfaces are configured
+    _timeout=15
+    while [ "$_timeout" -gt 0 ]; do
+        # we do ignore successful/failed states
+        if ! networkctl list --no-legend | grep -Eqiv 'unmanaged|configured|failed|linger'; then
+            break
+        fi
+
+        _timeout=$(( _timeout - 1 ))
+        sleep 1
+    done
+}
 
 #
 # helper functions
@@ -91,6 +102,7 @@ export gateway6
 export method
 export method6
 export metric
+export metric6
 export dns
 export search_domains
 export external
@@ -177,7 +189,6 @@ EOT
             ;;
     esac
 
-    # VH-TODO: Support IPv6 privacy
     cat <<EOT
 [Network]
 IPv6PrivacyExtensions=no
@@ -223,6 +234,10 @@ EOT
 
     if [ -n "$gateway6" ]; then
         echo "Gateway=${gateway6}"
+
+        if [ -n "$metric6" ]; then
+            echo "Metric=${metric6}"
+        fi
     fi
 
     if [ -n "$ip6_ula" ]; then
