F #227: WIP

diff --git a/src/etc/one-context.d/loc-10-network.d/netcfg-netplan b/src/etc/one-context.d/loc-10-network.d/netcfg-netplan
--- a/src/etc/one-context.d/loc-10-network.d/netcfg-netplan
+++ b/src/etc/one-context.d/loc-10-network.d/netcfg-netplan
@@ -32,6 +32,7 @@ configure_network()
     gen_resolvconf
     gen_network_configuration > /etc/netplan/00-opennebula-generated-network.yaml
     netplan generate
+    nm_symlink_run_connections
 }
 
 stop_network()
@@ -44,12 +45,14 @@ start_network()
     # VH-TODO: maybe generate >> networking start >> apply?
     service networking start
     netplan generate
+    nm_symlink_run_connections
     netplan apply
 }
 
 reload_network()
 {
     netplan generate
+    nm_symlink_run_connections
     netplan apply
 }
 
@@ -172,6 +175,11 @@ EOT
       dhcp6: true
 EOT
     fi
+
+    # VH-TODO: support configurable privacy
+    cat <<EOT
+      ipv6-privacy: false
+EOT
 }
 
 gen_ipv6_disable()
@@ -180,6 +188,41 @@ gen_ipv6_disable()
       accept-ra: false
       link-local: []
 EOT
+}
+
+# Old NM doesn't read from /run/NetworkManager/system-connections,
+# so the generated Netplan configuration is not respected. As a workaround,
+# we symlink the connection files into /etc
+nm_symlink_run_connections()
+{
+    if [ -n "${NETCFG_NETPLAN_RENDERER}" ] && \
+       [ "${NETCFG_NETPLAN_RENDERER}" != 'NetworkManager' ];
+    then
+        return
+    fi
+
+    if ! [ -d /run/NetworkManager/system-connections ]; then
+        return
+    fi
+
+    # cleanup any old symlinks
+    rm -f /etc/NetworkManager/system-connections/netplan-eth*
+
+    # VH-TODO: Simplify test only for Debian 10
+    case "$(NetworkManager --version 2>/dev/null)" in
+        1.14.*) # Debian 10
+            echo "WARNING: Symlinking NM's ephemeral connections into /etc" >&2
+            ;;
+        *)
+            return
+            ;;
+    esac
+
+    # symlink any Netplan connection files
+    for SRC in /run/NetworkManager/system-connections/netplan-eth*; do
+        DST="/etc/NetworkManager/system-connections/$(basename "${SRC}")"
+        ln -s "${SRC}" "${DST}"
+    done
 }
 
 init_netplan_renderer()
@@ -197,10 +240,15 @@ gen_network_configuration()
 {
     init_netplan_renderer
 
+    if [ "${NETCFG_NETPLAN_RENDERER}" = 'NetworkManager' ]; then
+        nm_enable
+    fi
+
     # TODO: consider to change the default to more robust NetworkManager - the
     # netplan's renderer default is networkd which may encounter issues with
     # version 248
     cat <<EOT
+# Generated by one-context
 network:
   version: 2
   renderer: ${NETCFG_NETPLAN_RENDERER:-networkd}
diff --git a/src/etc/one-context.d/loc-10-network.d/netcfg-networkd b/src/etc/one-context.d/loc-10-network.d/netcfg-networkd
--- a/src/etc/one-context.d/loc-10-network.d/netcfg-networkd
+++ b/src/etc/one-context.d/loc-10-network.d/netcfg-networkd
@@ -41,13 +41,32 @@ stop_network()
 start_network()
 {
     systemctl start systemd-networkd.service
+
+    # Dummy query waits until networkd is running
+    networkctl list >/dev/null
 }
 
 reload_network()
 {
-    # VH-TODO: Maybe networkctl reload && networkctl reconfigure with fallback to:
+    # VH-TODO: networkctl reload && networkctl reconfigure ethX
     systemctl restart systemd-networkd.service
+
+    # Dummy query waits until networkd is running
+    networkctl list >/dev/null
 }
+
+# # VH-TODO: deosn't have to be 100% reliable
+# wait_online()
+# {
+#     # Dummy query waits until networkd is running
+#     networkctl list >/dev/null
+#
+#     if [ -x /lib/systemd/systemd-networkd-wait-online ]; then
+#         /lib/systemd/systemd-networkd-wait-online --timeout=30
+#     else
+#         echo "ERROR [!]: Can't wait for online state, systemd-networkd-wait-online not found" >&2
+#     fi
+# }
 
 #
 # helper functions
@@ -157,6 +176,12 @@ DHCPv6Client=no
 EOT
             ;;
     esac
+
+    # VH-TODO: Support IPv6 privacy
+    cat <<EOT
+[Network]
+IPv6PrivacyExtensions=no
+EOT
 
     echo ""
 }
@@ -268,9 +293,9 @@ gen_network_configuration()
         #
         # This occurs at least with systemd/networkd version 248, which is on
         # Cent OS 8 for example.
-        if networkd_iface_managed "${dev}" ; then
+        if is_networkd_iface_managed "${dev}" ; then
             # networkctl up/down is not on ubuntu <21.04
-            networkctl down "$dev" || true
+            networkctl down "$dev" 2>/dev/null || true
 
             # this is still necessary to really unconfigure the interface
             ip addr flush "$dev"
@@ -278,6 +303,7 @@ gen_network_configuration()
 
         {
             cat <<EOT
+# Generated by one-context
 [Match]
 Name=${dev}
 EOT
